name: Rust Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'client/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'client/**'

jobs:
  build_rust:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install FFmpeg and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavutil-dev pkg-config

      - name: Set PKG_CONFIG_PATH
        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - name: Debug pkg-config
        run: pkg-config --list-all

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        working-directory: client
        run: cargo build --verbose

      - name: Test
        working-directory: client
        run: cargo test --verbose
