name: Rust Build on Windows

on:
  push:
    branches: [ "main" ]
    paths:
      - 'client/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'client/**'

jobs:
  build_rust:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
        shell: cmd

      - name: Install FFmpeg via vcpkg
        run: |
          cd vcpkg
          .\vcpkg.exe install ffmpeg[core]:x64-windows
        shell: cmd

      - name: Set vcpkg environment variables
        run: |
          echo "VCPKG_ROOT=$(System.DefaultWorkingDirectory)\vcpkg" >> $Env:GITHUB_ENV
          echo "VCPKG_CHAINLOAD_TOOLCHAIN_FILE=$(System.DefaultWorkingDirectory)\vcpkg\scripts\buildsystems\vcpkg.cmake" >> $Env:GITHUB_ENV
        shell: powershell

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        working-directory: client
        run: cargo build --verbose
        shell: powershell

