name: Rust Build on Windows

on:
  push:
    branches: ["main"]
    paths:
      - "client/**"
  pull_request:
    branches: ["main"]
    paths:
      - "client/**"

jobs:
  build_rust:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # 1. 安装 vcpkg
      - name: Install vcpkg
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat -disableMetrics

      # 2. 安装 FFmpeg (使用动态链接的 x64-windows triplet)
      - name: Install FFmpeg
        shell: cmd
        run: |
          cd vcpkg
          .\vcpkg.exe install ffmpeg[core,avcodec,avdevice,avfilter,avformat,swresample,swscale]:x64-windows

      # 3. 设置构建环境变量
      - name: Setup environment
        shell: powershell
        run: |
          $vcpkgRoot = "$env:GITHUB_WORKSPACE\vcpkg"
          $ffmpegDir = "$vcpkgRoot\installed\x64-windows"
          
          # 设置 vcpkg 相关变量
          echo "VCPKG_ROOT=$vcpkgRoot" >> $Env:GITHUB_ENV
          echo "VCPKGRS_DYNAMIC=1" >> $Env:GITHUB_ENV
          echo "VCPKGRS_TRIPLET=x64-windows" >> $Env:GITHUB_ENV
          
          # 设置 FFmpeg 路径
          echo "FFMPEG_DIR=$ffmpegDir" >> $Env:GITHUB_ENV
          echo "PKG_CONFIG_PATH=$ffmpegDir\lib\pkgconfig" >> $Env:GITHUB_ENV
          
          # 将 FFmpeg 的 bin 目录添加到 PATH
          echo "Path=$ffmpegDir\bin;$env:Path" >> $Env:GITHUB_ENV

      # 4. 安装 Rust 工具链
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-src, rustc-dev

      # 5. 构建项目
      - name: Build with Cargo
        working-directory: client
        shell: cmd
        run: |
          cargo clean
          cargo build --verbose
        env:
          RUST_BACKTRACE: full